name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # نسخه PHP پروژه‌تان
        extensions: mbstring, pdo, bcmath
        coverage: none

    # Step 3: Set up Composer
    - name: Install dependencies with Composer
      run: composer install --prefer-dist --no-progress --no-suggest

    # Step 4: Set up application environment
    - name: Set up environment
      run: |
        cp .env.example .env.testing 
        php artisan key:generate --env=testing

    # Step 5: Run migrations
    - name: Run migrations
      run: php artisan migrate --seed --env=testing

    # Step 6: Run tests
    - name: Run tests
      run: php artisan test --env=testing
